# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
    - develop

jobs:
- job: Windows

  pool:
    vmImage: 'vs2017-win2016'

  strategy:
    matrix:
      node_10_x:
        node_version: 10.x
  steps:
  - script: |
      git submodule init
    displayName: 'git submodule init'
  - script: |
      git submodule update
    displayName: 'Blob UploaderのClone'
  - script: |
      cd $(System.DefaultWorkingDirectory)/Blob-Uploader & npm i
    displayName: 'Blob Uploaderの依存パッケージ追加'
  - script: |
      cd $(System.DefaultWorkingDirectory) & yarn
    displayName: 'node moduleをインストール'
  - script: |
      yarn package:windows
    displayName: 'Windowsインストーラー作成'
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
    inputs:
      Contents: |
        $(System.DefaultWorkingDirectory)/Blob-Uploader/**/*
        $(System.DefaultWorkingDirectory)/dist/*.msi
      TargetFolder: $(Build.ArtifactStagingDirectory)/drop
  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifacts: Installer and Blob-Uploader'
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)/drop
      artifactName: drop