# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
    - delivery/*

jobs:
- job: Windows

  pool:
    vmImage: 'vs2017-win2016'

  strategy:
    matrix:
      node_10_x:
        node_version: 10.x
  steps:
  - script: |
      yarn install --network-timeout 1000000
    displayName: 'node moduleをインストール'
  - script: |
      yarn package:windows
    displayName: 'Windowsインストーラー作成'
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
    inputs:
      Contents: |
        $(System.DefaultWorkingDirectory)/dist/*.msi
      TargetFolder: $(Build.ArtifactStagingDirectory)/drop
  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifacts: Installer'
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)/drop
      artifactName: drop