enum AppActionType {
  POST_FEELING_AND_CAUSES_LOG_REQUEST = 'POST_FEELING_AND_CAUSES_REQUEST',
  POST_FEELING_AND_CAUSES_LOG_SUCCEEDED = 'POST_FEELING_AND_CAUSES_LOG_SUCCEEDED',
  POST_FEELING_AND_CAUSES_LOG_FAILED = 'POST_FEELING_AND_CAUSES_LOG_FAILED',
}

export default AppActionType;
