enum AppActionType {
  POST_MOOD_AND_CAUSES_LOG_REQUEST = 'POST_MOOD_AND_CAUSES_REQUEST',
  POST_MOOD_AND_CAUSES_LOG_SUCCEEDED = 'POST_MOOD_AND_CAUSES_LOG_SUCCEEDED',
  POST_MOOD_AND_CAUSES_LOG_FAILED = 'POST_MOOD_AND_CAUSES_LOG_FAILED',
}

export default AppActionType;
