enum FeelingActionType {
    FETCH_FEELING_REQUEST = 'FETCH_FEELING_REQUEST',
    FETCH_FEELING_SUCCEEDED = 'FETCH_FEELING_SUCCEEDED',
    FETCH_FEELING_FAILED = 'FETCH_FEELING_FAILED'
}

export default FeelingActionType;
