enum FeelingAndCausesActionType {
  GET_FEELINGS_REQUEST = 'GET_FEELINGS_REQUEST',
  GET_FEELINGS_SUCCEEDED = 'GET_FEELINGS_SUCCEEDED',
  GET_FEELINGS_FAILED = 'GET_FEELINGS_FAILED',

  GET_CAUSES_REQUEST = 'GET_CAUSES_REQUEST',
  GET_CAUSES_SUCCEEDED = 'GET_CAUSES_SUCCEEDED',
  GET_CAUSES_FAILED = 'GET_CAUSES_FAILED',

  POST_FEELING_AND_CAUSES_REQUEST = 'POST_FEELING_AND_CAUSES_REQUEST',
  POST_FEELING_AND_CAUSES_SUCCEEDED = 'POST_FEELING_AND_CAUSES_REQUEST',
  POST_FEELING_AND_CAUSES_FAILED = 'POST_FEELING_AND_CAUSES_REQUEST',
}

export default FeelingAndCausesActionType;
