enum PunchlogActionType {
  POST_PUNCHLOG_REQUEST = 'POST_PUNCHLOG_REQUEST',
  POST_PUNCHLOG_SUCCEEDED = 'POST_PUNCHLOG_SUCCEEDED',
  POST_PUNCHLOG_FAILED = 'POST_PUNCHLOG_FAILED',
}

export default PunchlogActionType;
