enum CauseOfFeelingActionType {
    FETCH_CAUSE_FEELING_REQUEST = 'FETCH_CAUSE_FEELING_REQUEST',
    FETCH_CAUSE_FEELING_SUCCEEDED = 'FETCH_CAUSE_FEELING_SUCCEEDED',
    FETCH_CAUSE_FEELING_FAILED = 'FETCH_CAUSE_FEELING_FAILED'
}

export default CauseOfFeelingActionType;
