enum MoodsActionType {
  GET_MOODS_REQUEST = 'GET_MOODS_REQUEST',
  GET_MOODS_SUCCEEDED = 'GET_MOODS_SUCCEEDED',
  GET_MOODS_FAILED = 'GET_MOODS_FAILED',
  SELECT_MOOD = 'SELECT_MOOD',
}

export default MoodsActionType;
