enum CausesActionType {
  GET_CAUSES_REQUEST = 'GET_CAUSES_REQUEST',
  GET_CAUSES_SUCCEEDED = 'GET_CAUSES_SUCCEEDED',
  GET_CAUSES_FAILED = 'GET_CAUSES_FAILED',
  TOGGLE_CAUSES = 'TOGGLE_CAUSES',
}

export default CausesActionType;
