export enum ScreenActionType {
    SWITCH_INPUT_FEELING = 'SWITCH_INPUT_FEELING',
    SWITCH_INPUT_CAUSE_OF_FEELING = 'SWITCH_INPUT_CAUSE_OF_FEELING',
    SWITCH_RESULT = 'SWITCH_RESULT'
}

export default ScreenActionType;
